---
apiVersion: k8up.io/v1
kind: PreBackupPod
metadata:
  name: bad-exit-prebackup
  namespace: k8up-e2e-subject
spec:
  backupCommand: "exit 1"
  pod:
    spec:
      containers:
        - image: busybox
          name: busybox-sleep
          command:
            - 'sleep'
            - 'infinity'
